/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCaptureRouteImport } from './routes/_authed/capture'
import { Route as AuthedContactsRouteRouteImport } from './routes/_authed/contacts/route'
import { Route as AuthedDealsRouteRouteImport } from './routes/_authed/deals/route'
import { Route as AuthedDocumentsRouteRouteImport } from './routes/_authed/documents/route'
import { Route as AuthedInboxRouteRouteImport } from './routes/_authed/inbox/route'
import { Route as AuthedInteractionsRouteRouteImport } from './routes/_authed/interactions/route'
import { Route as AuthedNumbersRouteImport } from './routes/_authed/numbers'
import { Route as AuthedOrganizationsRouteRouteImport } from './routes/_authed/organizations/route'
import { Route as AuthedProjectsRouteRouteImport } from './routes/_authed/projects/route'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedSystemRouteImport } from './routes/_authed/system'
import { Route as AuthedTasksRouteRouteImport } from './routes/_authed/tasks/route'
import { Route as AuthedWatchesRouteRouteImport } from './routes/_authed/watches/route'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed/account/index'
import { Route as AuthedAccountMfaRouteImport } from './routes/_authed/account/mfa'
import { Route as AuthedAccountPasswordRouteImport } from './routes/_authed/account/password'
import { Route as AuthedContactsIndexRouteImport } from './routes/_authed/contacts/index'
import { Route as AuthedContactsNewRouteImport } from './routes/_authed/contacts/new'
import { Route as AuthedContactsScanRouteImport } from './routes/_authed/contacts/scan'
import { Route as AuthedDealsIndexRouteImport } from './routes/_authed/deals/index'
import { Route as AuthedDealsNewRouteImport } from './routes/_authed/deals/new'
import { Route as AuthedDocumentsIndexRouteImport } from './routes/_authed/documents/index'
import { Route as AuthedDocumentsDocumentIdRouteImport } from './routes/_authed/documents/$documentId'
import { Route as AuthedDocumentsNewRouteImport } from './routes/_authed/documents/new'
import { Route as AuthedInboxIndexRouteImport } from './routes/_authed/inbox/index'
import { Route as AuthedInboxCaptureIdRouteImport } from './routes/_authed/inbox/$captureId'
import { Route as AuthedInteractionsIndexRouteImport } from './routes/_authed/interactions/index'
import { Route as AuthedInteractionsInteractionIdRouteImport } from './routes/_authed/interactions/$interactionId'
import { Route as AuthedInteractionsNewRouteImport } from './routes/_authed/interactions/new'
import { Route as AuthedOrganizationsIndexRouteImport } from './routes/_authed/organizations/index'
import { Route as AuthedOrganizationsNewRouteImport } from './routes/_authed/organizations/new'
import { Route as AuthedProjectsIndexRouteImport } from './routes/_authed/projects/index'
import { Route as AuthedProjectsNewRouteImport } from './routes/_authed/projects/new'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedTasksTaskIdRouteImport } from './routes/_authed/tasks/$taskId'
import { Route as AuthedTasksNewRouteImport } from './routes/_authed/tasks/new'
import { Route as AuthedWatchesIndexRouteImport } from './routes/_authed/watches/index'
import { Route as AuthedWatchesNewRouteImport } from './routes/_authed/watches/new'
import { Route as AuthedContactsContactIdIndexRouteImport } from './routes/_authed/contacts/$contactId/index'
import { Route as AuthedContactsContactIdEditRouteImport } from './routes/_authed/contacts/$contactId/edit'
import { Route as AuthedDealsDealIdIndexRouteImport } from './routes/_authed/deals/$dealId/index'
import { Route as AuthedDealsDealIdEditRouteImport } from './routes/_authed/deals/$dealId/edit'
import { Route as AuthedOrganizationsOrganizationIdIndexRouteImport } from './routes/_authed/organizations/$organizationId/index'
import { Route as AuthedOrganizationsOrganizationIdEditRouteImport } from './routes/_authed/organizations/$organizationId/edit'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as AuthedProjectsProjectIdEditRouteImport } from './routes/_authed/projects/$projectId/edit'
import { Route as AuthedWatchesWatchIdIndexRouteImport } from './routes/_authed/watches/$watchId/index'
import { Route as AuthedWatchesWatchIdEditRouteImport } from './routes/_authed/watches/$watchId/edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCaptureRoute = AuthedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsRouteRoute = AuthedContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDealsRouteRoute = AuthedDealsRouteRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsRouteRoute = AuthedDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInboxRouteRoute = AuthedInboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInteractionsRouteRoute = AuthedInteractionsRouteRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNumbersRoute = AuthedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrganizationsRouteRoute =
  AuthedOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsRouteRoute = AuthedProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemRoute = AuthedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRouteRoute = AuthedTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWatchesRouteRoute = AuthedWatchesRouteRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountMfaRoute = AuthedAccountMfaRouteImport.update({
  id: '/account/mfa',
  path: '/account/mfa',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountPasswordRoute = AuthedAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsIndexRoute = AuthedContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedContactsRouteRoute,
} as any)
const AuthedContactsNewRoute = AuthedContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedContactsRouteRoute,
} as any)
const AuthedContactsScanRoute = AuthedContactsScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthedContactsRouteRoute,
} as any)
const AuthedDealsIndexRoute = AuthedDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDealsRouteRoute,
} as any)
const AuthedDealsNewRoute = AuthedDealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedDealsRouteRoute,
} as any)
const AuthedDocumentsIndexRoute = AuthedDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDocumentsRouteRoute,
} as any)
const AuthedDocumentsDocumentIdRoute =
  AuthedDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthedDocumentsRouteRoute,
  } as any)
const AuthedDocumentsNewRoute = AuthedDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedDocumentsRouteRoute,
} as any)
const AuthedInboxIndexRoute = AuthedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedInboxRouteRoute,
} as any)
const AuthedInboxCaptureIdRoute = AuthedInboxCaptureIdRouteImport.update({
  id: '/$captureId',
  path: '/$captureId',
  getParentRoute: () => AuthedInboxRouteRoute,
} as any)
const AuthedInteractionsIndexRoute = AuthedInteractionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedInteractionsRouteRoute,
} as any)
const AuthedInteractionsInteractionIdRoute =
  AuthedInteractionsInteractionIdRouteImport.update({
    id: '/$interactionId',
    path: '/$interactionId',
    getParentRoute: () => AuthedInteractionsRouteRoute,
  } as any)
const AuthedInteractionsNewRoute = AuthedInteractionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedInteractionsRouteRoute,
} as any)
const AuthedOrganizationsIndexRoute =
  AuthedOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrganizationsRouteRoute,
  } as any)
const AuthedOrganizationsNewRoute = AuthedOrganizationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedOrganizationsRouteRoute,
} as any)
const AuthedProjectsIndexRoute = AuthedProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProjectsRouteRoute,
} as any)
const AuthedProjectsNewRoute = AuthedProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedProjectsRouteRoute,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTasksRouteRoute,
} as any)
const AuthedTasksTaskIdRoute = AuthedTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AuthedTasksRouteRoute,
} as any)
const AuthedTasksNewRoute = AuthedTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedTasksRouteRoute,
} as any)
const AuthedWatchesIndexRoute = AuthedWatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWatchesRouteRoute,
} as any)
const AuthedWatchesNewRoute = AuthedWatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedWatchesRouteRoute,
} as any)
const AuthedContactsContactIdIndexRoute =
  AuthedContactsContactIdIndexRouteImport.update({
    id: '/$contactId/',
    path: '/$contactId/',
    getParentRoute: () => AuthedContactsRouteRoute,
  } as any)
const AuthedContactsContactIdEditRoute =
  AuthedContactsContactIdEditRouteImport.update({
    id: '/$contactId/edit',
    path: '/$contactId/edit',
    getParentRoute: () => AuthedContactsRouteRoute,
  } as any)
const AuthedDealsDealIdIndexRoute = AuthedDealsDealIdIndexRouteImport.update({
  id: '/$dealId/',
  path: '/$dealId/',
  getParentRoute: () => AuthedDealsRouteRoute,
} as any)
const AuthedDealsDealIdEditRoute = AuthedDealsDealIdEditRouteImport.update({
  id: '/$dealId/edit',
  path: '/$dealId/edit',
  getParentRoute: () => AuthedDealsRouteRoute,
} as any)
const AuthedOrganizationsOrganizationIdIndexRoute =
  AuthedOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/$organizationId/',
    path: '/$organizationId/',
    getParentRoute: () => AuthedOrganizationsRouteRoute,
  } as any)
const AuthedOrganizationsOrganizationIdEditRoute =
  AuthedOrganizationsOrganizationIdEditRouteImport.update({
    id: '/$organizationId/edit',
    path: '/$organizationId/edit',
    getParentRoute: () => AuthedOrganizationsRouteRoute,
  } as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => AuthedProjectsRouteRoute,
  } as any)
const AuthedProjectsProjectIdEditRoute =
  AuthedProjectsProjectIdEditRouteImport.update({
    id: '/$projectId/edit',
    path: '/$projectId/edit',
    getParentRoute: () => AuthedProjectsRouteRoute,
  } as any)
const AuthedWatchesWatchIdIndexRoute =
  AuthedWatchesWatchIdIndexRouteImport.update({
    id: '/$watchId/',
    path: '/$watchId/',
    getParentRoute: () => AuthedWatchesRouteRoute,
  } as any)
const AuthedWatchesWatchIdEditRoute =
  AuthedWatchesWatchIdEditRouteImport.update({
    id: '/$watchId/edit',
    path: '/$watchId/edit',
    getParentRoute: () => AuthedWatchesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/contacts': typeof AuthedContactsRouteRouteWithChildren
  '/deals': typeof AuthedDealsRouteRouteWithChildren
  '/documents': typeof AuthedDocumentsRouteRouteWithChildren
  '/inbox': typeof AuthedInboxRouteRouteWithChildren
  '/interactions': typeof AuthedInteractionsRouteRouteWithChildren
  '/organizations': typeof AuthedOrganizationsRouteRouteWithChildren
  '/projects': typeof AuthedProjectsRouteRouteWithChildren
  '/tasks': typeof AuthedTasksRouteRouteWithChildren
  '/watches': typeof AuthedWatchesRouteRouteWithChildren
  '/capture': typeof AuthedCaptureRoute
  '/numbers': typeof AuthedNumbersRoute
  '/search': typeof AuthedSearchRoute
  '/system': typeof AuthedSystemRoute
  '/account/mfa': typeof AuthedAccountMfaRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/contacts/new': typeof AuthedContactsNewRoute
  '/contacts/scan': typeof AuthedContactsScanRoute
  '/deals/new': typeof AuthedDealsNewRoute
  '/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/documents/new': typeof AuthedDocumentsNewRoute
  '/inbox/$captureId': typeof AuthedInboxCaptureIdRoute
  '/interactions/$interactionId': typeof AuthedInteractionsInteractionIdRoute
  '/interactions/new': typeof AuthedInteractionsNewRoute
  '/organizations/new': typeof AuthedOrganizationsNewRoute
  '/projects/new': typeof AuthedProjectsNewRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/watches/new': typeof AuthedWatchesNewRoute
  '/account/': typeof AuthedAccountIndexRoute
  '/contacts/': typeof AuthedContactsIndexRoute
  '/deals/': typeof AuthedDealsIndexRoute
  '/documents/': typeof AuthedDocumentsIndexRoute
  '/inbox/': typeof AuthedInboxIndexRoute
  '/interactions/': typeof AuthedInteractionsIndexRoute
  '/organizations/': typeof AuthedOrganizationsIndexRoute
  '/projects/': typeof AuthedProjectsIndexRoute
  '/tasks/': typeof AuthedTasksIndexRoute
  '/watches/': typeof AuthedWatchesIndexRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/deals/$dealId/edit': typeof AuthedDealsDealIdEditRoute
  '/organizations/$organizationId/edit': typeof AuthedOrganizationsOrganizationIdEditRoute
  '/projects/$projectId/edit': typeof AuthedProjectsProjectIdEditRoute
  '/watches/$watchId/edit': typeof AuthedWatchesWatchIdEditRoute
  '/contacts/$contactId/': typeof AuthedContactsContactIdIndexRoute
  '/deals/$dealId/': typeof AuthedDealsDealIdIndexRoute
  '/organizations/$organizationId/': typeof AuthedOrganizationsOrganizationIdIndexRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/watches/$watchId/': typeof AuthedWatchesWatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/capture': typeof AuthedCaptureRoute
  '/numbers': typeof AuthedNumbersRoute
  '/search': typeof AuthedSearchRoute
  '/system': typeof AuthedSystemRoute
  '/': typeof AuthedIndexRoute
  '/account/mfa': typeof AuthedAccountMfaRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/contacts/new': typeof AuthedContactsNewRoute
  '/contacts/scan': typeof AuthedContactsScanRoute
  '/deals/new': typeof AuthedDealsNewRoute
  '/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/documents/new': typeof AuthedDocumentsNewRoute
  '/inbox/$captureId': typeof AuthedInboxCaptureIdRoute
  '/interactions/$interactionId': typeof AuthedInteractionsInteractionIdRoute
  '/interactions/new': typeof AuthedInteractionsNewRoute
  '/organizations/new': typeof AuthedOrganizationsNewRoute
  '/projects/new': typeof AuthedProjectsNewRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/tasks/new': typeof AuthedTasksNewRoute
  '/watches/new': typeof AuthedWatchesNewRoute
  '/account': typeof AuthedAccountIndexRoute
  '/contacts': typeof AuthedContactsIndexRoute
  '/deals': typeof AuthedDealsIndexRoute
  '/documents': typeof AuthedDocumentsIndexRoute
  '/inbox': typeof AuthedInboxIndexRoute
  '/interactions': typeof AuthedInteractionsIndexRoute
  '/organizations': typeof AuthedOrganizationsIndexRoute
  '/projects': typeof AuthedProjectsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/watches': typeof AuthedWatchesIndexRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/deals/$dealId/edit': typeof AuthedDealsDealIdEditRoute
  '/organizations/$organizationId/edit': typeof AuthedOrganizationsOrganizationIdEditRoute
  '/projects/$projectId/edit': typeof AuthedProjectsProjectIdEditRoute
  '/watches/$watchId/edit': typeof AuthedWatchesWatchIdEditRoute
  '/contacts/$contactId': typeof AuthedContactsContactIdIndexRoute
  '/deals/$dealId': typeof AuthedDealsDealIdIndexRoute
  '/organizations/$organizationId': typeof AuthedOrganizationsOrganizationIdIndexRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
  '/watches/$watchId': typeof AuthedWatchesWatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/contacts': typeof AuthedContactsRouteRouteWithChildren
  '/_authed/deals': typeof AuthedDealsRouteRouteWithChildren
  '/_authed/documents': typeof AuthedDocumentsRouteRouteWithChildren
  '/_authed/inbox': typeof AuthedInboxRouteRouteWithChildren
  '/_authed/interactions': typeof AuthedInteractionsRouteRouteWithChildren
  '/_authed/organizations': typeof AuthedOrganizationsRouteRouteWithChildren
  '/_authed/projects': typeof AuthedProjectsRouteRouteWithChildren
  '/_authed/tasks': typeof AuthedTasksRouteRouteWithChildren
  '/_authed/watches': typeof AuthedWatchesRouteRouteWithChildren
  '/_authed/capture': typeof AuthedCaptureRoute
  '/_authed/numbers': typeof AuthedNumbersRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/system': typeof AuthedSystemRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/account/mfa': typeof AuthedAccountMfaRoute
  '/_authed/account/password': typeof AuthedAccountPasswordRoute
  '/_authed/contacts/new': typeof AuthedContactsNewRoute
  '/_authed/contacts/scan': typeof AuthedContactsScanRoute
  '/_authed/deals/new': typeof AuthedDealsNewRoute
  '/_authed/documents/$documentId': typeof AuthedDocumentsDocumentIdRoute
  '/_authed/documents/new': typeof AuthedDocumentsNewRoute
  '/_authed/inbox/$captureId': typeof AuthedInboxCaptureIdRoute
  '/_authed/interactions/$interactionId': typeof AuthedInteractionsInteractionIdRoute
  '/_authed/interactions/new': typeof AuthedInteractionsNewRoute
  '/_authed/organizations/new': typeof AuthedOrganizationsNewRoute
  '/_authed/projects/new': typeof AuthedProjectsNewRoute
  '/_authed/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/_authed/tasks/new': typeof AuthedTasksNewRoute
  '/_authed/watches/new': typeof AuthedWatchesNewRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
  '/_authed/contacts/': typeof AuthedContactsIndexRoute
  '/_authed/deals/': typeof AuthedDealsIndexRoute
  '/_authed/documents/': typeof AuthedDocumentsIndexRoute
  '/_authed/inbox/': typeof AuthedInboxIndexRoute
  '/_authed/interactions/': typeof AuthedInteractionsIndexRoute
  '/_authed/organizations/': typeof AuthedOrganizationsIndexRoute
  '/_authed/projects/': typeof AuthedProjectsIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/watches/': typeof AuthedWatchesIndexRoute
  '/_authed/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/_authed/deals/$dealId/edit': typeof AuthedDealsDealIdEditRoute
  '/_authed/organizations/$organizationId/edit': typeof AuthedOrganizationsOrganizationIdEditRoute
  '/_authed/projects/$projectId/edit': typeof AuthedProjectsProjectIdEditRoute
  '/_authed/watches/$watchId/edit': typeof AuthedWatchesWatchIdEditRoute
  '/_authed/contacts/$contactId/': typeof AuthedContactsContactIdIndexRoute
  '/_authed/deals/$dealId/': typeof AuthedDealsDealIdIndexRoute
  '/_authed/organizations/$organizationId/': typeof AuthedOrganizationsOrganizationIdIndexRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/_authed/watches/$watchId/': typeof AuthedWatchesWatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/contacts'
    | '/deals'
    | '/documents'
    | '/inbox'
    | '/interactions'
    | '/organizations'
    | '/projects'
    | '/tasks'
    | '/watches'
    | '/capture'
    | '/numbers'
    | '/search'
    | '/system'
    | '/account/mfa'
    | '/account/password'
    | '/contacts/new'
    | '/contacts/scan'
    | '/deals/new'
    | '/documents/$documentId'
    | '/documents/new'
    | '/inbox/$captureId'
    | '/interactions/$interactionId'
    | '/interactions/new'
    | '/organizations/new'
    | '/projects/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/watches/new'
    | '/account/'
    | '/contacts/'
    | '/deals/'
    | '/documents/'
    | '/inbox/'
    | '/interactions/'
    | '/organizations/'
    | '/projects/'
    | '/tasks/'
    | '/watches/'
    | '/contacts/$contactId/edit'
    | '/deals/$dealId/edit'
    | '/organizations/$organizationId/edit'
    | '/projects/$projectId/edit'
    | '/watches/$watchId/edit'
    | '/contacts/$contactId/'
    | '/deals/$dealId/'
    | '/organizations/$organizationId/'
    | '/projects/$projectId/'
    | '/watches/$watchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/capture'
    | '/numbers'
    | '/search'
    | '/system'
    | '/'
    | '/account/mfa'
    | '/account/password'
    | '/contacts/new'
    | '/contacts/scan'
    | '/deals/new'
    | '/documents/$documentId'
    | '/documents/new'
    | '/inbox/$captureId'
    | '/interactions/$interactionId'
    | '/interactions/new'
    | '/organizations/new'
    | '/projects/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/watches/new'
    | '/account'
    | '/contacts'
    | '/deals'
    | '/documents'
    | '/inbox'
    | '/interactions'
    | '/organizations'
    | '/projects'
    | '/tasks'
    | '/watches'
    | '/contacts/$contactId/edit'
    | '/deals/$dealId/edit'
    | '/organizations/$organizationId/edit'
    | '/projects/$projectId/edit'
    | '/watches/$watchId/edit'
    | '/contacts/$contactId'
    | '/deals/$dealId'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/watches/$watchId'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/contacts'
    | '/_authed/deals'
    | '/_authed/documents'
    | '/_authed/inbox'
    | '/_authed/interactions'
    | '/_authed/organizations'
    | '/_authed/projects'
    | '/_authed/tasks'
    | '/_authed/watches'
    | '/_authed/capture'
    | '/_authed/numbers'
    | '/_authed/search'
    | '/_authed/system'
    | '/_authed/'
    | '/_authed/account/mfa'
    | '/_authed/account/password'
    | '/_authed/contacts/new'
    | '/_authed/contacts/scan'
    | '/_authed/deals/new'
    | '/_authed/documents/$documentId'
    | '/_authed/documents/new'
    | '/_authed/inbox/$captureId'
    | '/_authed/interactions/$interactionId'
    | '/_authed/interactions/new'
    | '/_authed/organizations/new'
    | '/_authed/projects/new'
    | '/_authed/tasks/$taskId'
    | '/_authed/tasks/new'
    | '/_authed/watches/new'
    | '/_authed/account/'
    | '/_authed/contacts/'
    | '/_authed/deals/'
    | '/_authed/documents/'
    | '/_authed/inbox/'
    | '/_authed/interactions/'
    | '/_authed/organizations/'
    | '/_authed/projects/'
    | '/_authed/tasks/'
    | '/_authed/watches/'
    | '/_authed/contacts/$contactId/edit'
    | '/_authed/deals/$dealId/edit'
    | '/_authed/organizations/$organizationId/edit'
    | '/_authed/projects/$projectId/edit'
    | '/_authed/watches/$watchId/edit'
    | '/_authed/contacts/$contactId/'
    | '/_authed/deals/$dealId/'
    | '/_authed/organizations/$organizationId/'
    | '/_authed/projects/$projectId/'
    | '/_authed/watches/$watchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/capture': {
      id: '/_authed/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthedCaptureRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts': {
      id: '/_authed/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthedContactsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deals': {
      id: '/_authed/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthedDealsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents': {
      id: '/_authed/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthedDocumentsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/interactions': {
      id: '/_authed/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof AuthedInteractionsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/numbers': {
      id: '/_authed/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthedNumbersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/organizations': {
      id: '/_authed/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthedOrganizationsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system': {
      id: '/_authed/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthedSystemRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/watches': {
      id: '/_authed/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof AuthedWatchesRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/mfa': {
      id: '/_authed/account/mfa'
      path: '/account/mfa'
      fullPath: '/account/mfa'
      preLoaderRoute: typeof AuthedAccountMfaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/password': {
      id: '/_authed/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthedAccountPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts/': {
      id: '/_authed/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedContactsIndexRouteImport
      parentRoute: typeof AuthedContactsRouteRoute
    }
    '/_authed/contacts/new': {
      id: '/_authed/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthedContactsNewRouteImport
      parentRoute: typeof AuthedContactsRouteRoute
    }
    '/_authed/contacts/scan': {
      id: '/_authed/contacts/scan'
      path: '/scan'
      fullPath: '/contacts/scan'
      preLoaderRoute: typeof AuthedContactsScanRouteImport
      parentRoute: typeof AuthedContactsRouteRoute
    }
    '/_authed/deals/': {
      id: '/_authed/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthedDealsIndexRouteImport
      parentRoute: typeof AuthedDealsRouteRoute
    }
    '/_authed/deals/new': {
      id: '/_authed/deals/new'
      path: '/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AuthedDealsNewRouteImport
      parentRoute: typeof AuthedDealsRouteRoute
    }
    '/_authed/documents/': {
      id: '/_authed/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthedDocumentsIndexRouteImport
      parentRoute: typeof AuthedDocumentsRouteRoute
    }
    '/_authed/documents/$documentId': {
      id: '/_authed/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthedDocumentsRouteRoute
    }
    '/_authed/documents/new': {
      id: '/_authed/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthedDocumentsNewRouteImport
      parentRoute: typeof AuthedDocumentsRouteRoute
    }
    '/_authed/inbox/': {
      id: '/_authed/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthedInboxIndexRouteImport
      parentRoute: typeof AuthedInboxRouteRoute
    }
    '/_authed/inbox/$captureId': {
      id: '/_authed/inbox/$captureId'
      path: '/$captureId'
      fullPath: '/inbox/$captureId'
      preLoaderRoute: typeof AuthedInboxCaptureIdRouteImport
      parentRoute: typeof AuthedInboxRouteRoute
    }
    '/_authed/interactions/': {
      id: '/_authed/interactions/'
      path: '/'
      fullPath: '/interactions/'
      preLoaderRoute: typeof AuthedInteractionsIndexRouteImport
      parentRoute: typeof AuthedInteractionsRouteRoute
    }
    '/_authed/interactions/$interactionId': {
      id: '/_authed/interactions/$interactionId'
      path: '/$interactionId'
      fullPath: '/interactions/$interactionId'
      preLoaderRoute: typeof AuthedInteractionsInteractionIdRouteImport
      parentRoute: typeof AuthedInteractionsRouteRoute
    }
    '/_authed/interactions/new': {
      id: '/_authed/interactions/new'
      path: '/new'
      fullPath: '/interactions/new'
      preLoaderRoute: typeof AuthedInteractionsNewRouteImport
      parentRoute: typeof AuthedInteractionsRouteRoute
    }
    '/_authed/organizations/': {
      id: '/_authed/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthedOrganizationsIndexRouteImport
      parentRoute: typeof AuthedOrganizationsRouteRoute
    }
    '/_authed/organizations/new': {
      id: '/_authed/organizations/new'
      path: '/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AuthedOrganizationsNewRouteImport
      parentRoute: typeof AuthedOrganizationsRouteRoute
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedProjectsIndexRouteImport
      parentRoute: typeof AuthedProjectsRouteRoute
    }
    '/_authed/projects/new': {
      id: '/_authed/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthedProjectsNewRouteImport
      parentRoute: typeof AuthedProjectsRouteRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedTasksRouteRoute
    }
    '/_authed/tasks/$taskId': {
      id: '/_authed/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthedTasksTaskIdRouteImport
      parentRoute: typeof AuthedTasksRouteRoute
    }
    '/_authed/tasks/new': {
      id: '/_authed/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthedTasksNewRouteImport
      parentRoute: typeof AuthedTasksRouteRoute
    }
    '/_authed/watches/': {
      id: '/_authed/watches/'
      path: '/'
      fullPath: '/watches/'
      preLoaderRoute: typeof AuthedWatchesIndexRouteImport
      parentRoute: typeof AuthedWatchesRouteRoute
    }
    '/_authed/watches/new': {
      id: '/_authed/watches/new'
      path: '/new'
      fullPath: '/watches/new'
      preLoaderRoute: typeof AuthedWatchesNewRouteImport
      parentRoute: typeof AuthedWatchesRouteRoute
    }
    '/_authed/contacts/$contactId/': {
      id: '/_authed/contacts/$contactId/'
      path: '/$contactId'
      fullPath: '/contacts/$contactId/'
      preLoaderRoute: typeof AuthedContactsContactIdIndexRouteImport
      parentRoute: typeof AuthedContactsRouteRoute
    }
    '/_authed/contacts/$contactId/edit': {
      id: '/_authed/contacts/$contactId/edit'
      path: '/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof AuthedContactsContactIdEditRouteImport
      parentRoute: typeof AuthedContactsRouteRoute
    }
    '/_authed/deals/$dealId/': {
      id: '/_authed/deals/$dealId/'
      path: '/$dealId'
      fullPath: '/deals/$dealId/'
      preLoaderRoute: typeof AuthedDealsDealIdIndexRouteImport
      parentRoute: typeof AuthedDealsRouteRoute
    }
    '/_authed/deals/$dealId/edit': {
      id: '/_authed/deals/$dealId/edit'
      path: '/$dealId/edit'
      fullPath: '/deals/$dealId/edit'
      preLoaderRoute: typeof AuthedDealsDealIdEditRouteImport
      parentRoute: typeof AuthedDealsRouteRoute
    }
    '/_authed/organizations/$organizationId/': {
      id: '/_authed/organizations/$organizationId/'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof AuthedOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AuthedOrganizationsRouteRoute
    }
    '/_authed/organizations/$organizationId/edit': {
      id: '/_authed/organizations/$organizationId/edit'
      path: '/$organizationId/edit'
      fullPath: '/organizations/$organizationId/edit'
      preLoaderRoute: typeof AuthedOrganizationsOrganizationIdEditRouteImport
      parentRoute: typeof AuthedOrganizationsRouteRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectsRouteRoute
    }
    '/_authed/projects/$projectId/edit': {
      id: '/_authed/projects/$projectId/edit'
      path: '/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthedProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthedProjectsRouteRoute
    }
    '/_authed/watches/$watchId/': {
      id: '/_authed/watches/$watchId/'
      path: '/$watchId'
      fullPath: '/watches/$watchId/'
      preLoaderRoute: typeof AuthedWatchesWatchIdIndexRouteImport
      parentRoute: typeof AuthedWatchesRouteRoute
    }
    '/_authed/watches/$watchId/edit': {
      id: '/_authed/watches/$watchId/edit'
      path: '/$watchId/edit'
      fullPath: '/watches/$watchId/edit'
      preLoaderRoute: typeof AuthedWatchesWatchIdEditRouteImport
      parentRoute: typeof AuthedWatchesRouteRoute
    }
  }
}

interface AuthedContactsRouteRouteChildren {
  AuthedContactsNewRoute: typeof AuthedContactsNewRoute
  AuthedContactsScanRoute: typeof AuthedContactsScanRoute
  AuthedContactsIndexRoute: typeof AuthedContactsIndexRoute
  AuthedContactsContactIdEditRoute: typeof AuthedContactsContactIdEditRoute
  AuthedContactsContactIdIndexRoute: typeof AuthedContactsContactIdIndexRoute
}

const AuthedContactsRouteRouteChildren: AuthedContactsRouteRouteChildren = {
  AuthedContactsNewRoute: AuthedContactsNewRoute,
  AuthedContactsScanRoute: AuthedContactsScanRoute,
  AuthedContactsIndexRoute: AuthedContactsIndexRoute,
  AuthedContactsContactIdEditRoute: AuthedContactsContactIdEditRoute,
  AuthedContactsContactIdIndexRoute: AuthedContactsContactIdIndexRoute,
}

const AuthedContactsRouteRouteWithChildren =
  AuthedContactsRouteRoute._addFileChildren(AuthedContactsRouteRouteChildren)

interface AuthedDealsRouteRouteChildren {
  AuthedDealsNewRoute: typeof AuthedDealsNewRoute
  AuthedDealsIndexRoute: typeof AuthedDealsIndexRoute
  AuthedDealsDealIdEditRoute: typeof AuthedDealsDealIdEditRoute
  AuthedDealsDealIdIndexRoute: typeof AuthedDealsDealIdIndexRoute
}

const AuthedDealsRouteRouteChildren: AuthedDealsRouteRouteChildren = {
  AuthedDealsNewRoute: AuthedDealsNewRoute,
  AuthedDealsIndexRoute: AuthedDealsIndexRoute,
  AuthedDealsDealIdEditRoute: AuthedDealsDealIdEditRoute,
  AuthedDealsDealIdIndexRoute: AuthedDealsDealIdIndexRoute,
}

const AuthedDealsRouteRouteWithChildren =
  AuthedDealsRouteRoute._addFileChildren(AuthedDealsRouteRouteChildren)

interface AuthedDocumentsRouteRouteChildren {
  AuthedDocumentsDocumentIdRoute: typeof AuthedDocumentsDocumentIdRoute
  AuthedDocumentsNewRoute: typeof AuthedDocumentsNewRoute
  AuthedDocumentsIndexRoute: typeof AuthedDocumentsIndexRoute
}

const AuthedDocumentsRouteRouteChildren: AuthedDocumentsRouteRouteChildren = {
  AuthedDocumentsDocumentIdRoute: AuthedDocumentsDocumentIdRoute,
  AuthedDocumentsNewRoute: AuthedDocumentsNewRoute,
  AuthedDocumentsIndexRoute: AuthedDocumentsIndexRoute,
}

const AuthedDocumentsRouteRouteWithChildren =
  AuthedDocumentsRouteRoute._addFileChildren(AuthedDocumentsRouteRouteChildren)

interface AuthedInboxRouteRouteChildren {
  AuthedInboxCaptureIdRoute: typeof AuthedInboxCaptureIdRoute
  AuthedInboxIndexRoute: typeof AuthedInboxIndexRoute
}

const AuthedInboxRouteRouteChildren: AuthedInboxRouteRouteChildren = {
  AuthedInboxCaptureIdRoute: AuthedInboxCaptureIdRoute,
  AuthedInboxIndexRoute: AuthedInboxIndexRoute,
}

const AuthedInboxRouteRouteWithChildren =
  AuthedInboxRouteRoute._addFileChildren(AuthedInboxRouteRouteChildren)

interface AuthedInteractionsRouteRouteChildren {
  AuthedInteractionsInteractionIdRoute: typeof AuthedInteractionsInteractionIdRoute
  AuthedInteractionsNewRoute: typeof AuthedInteractionsNewRoute
  AuthedInteractionsIndexRoute: typeof AuthedInteractionsIndexRoute
}

const AuthedInteractionsRouteRouteChildren: AuthedInteractionsRouteRouteChildren =
  {
    AuthedInteractionsInteractionIdRoute: AuthedInteractionsInteractionIdRoute,
    AuthedInteractionsNewRoute: AuthedInteractionsNewRoute,
    AuthedInteractionsIndexRoute: AuthedInteractionsIndexRoute,
  }

const AuthedInteractionsRouteRouteWithChildren =
  AuthedInteractionsRouteRoute._addFileChildren(
    AuthedInteractionsRouteRouteChildren,
  )

interface AuthedOrganizationsRouteRouteChildren {
  AuthedOrganizationsNewRoute: typeof AuthedOrganizationsNewRoute
  AuthedOrganizationsIndexRoute: typeof AuthedOrganizationsIndexRoute
  AuthedOrganizationsOrganizationIdEditRoute: typeof AuthedOrganizationsOrganizationIdEditRoute
  AuthedOrganizationsOrganizationIdIndexRoute: typeof AuthedOrganizationsOrganizationIdIndexRoute
}

const AuthedOrganizationsRouteRouteChildren: AuthedOrganizationsRouteRouteChildren =
  {
    AuthedOrganizationsNewRoute: AuthedOrganizationsNewRoute,
    AuthedOrganizationsIndexRoute: AuthedOrganizationsIndexRoute,
    AuthedOrganizationsOrganizationIdEditRoute:
      AuthedOrganizationsOrganizationIdEditRoute,
    AuthedOrganizationsOrganizationIdIndexRoute:
      AuthedOrganizationsOrganizationIdIndexRoute,
  }

const AuthedOrganizationsRouteRouteWithChildren =
  AuthedOrganizationsRouteRoute._addFileChildren(
    AuthedOrganizationsRouteRouteChildren,
  )

interface AuthedProjectsRouteRouteChildren {
  AuthedProjectsNewRoute: typeof AuthedProjectsNewRoute
  AuthedProjectsIndexRoute: typeof AuthedProjectsIndexRoute
  AuthedProjectsProjectIdEditRoute: typeof AuthedProjectsProjectIdEditRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
}

const AuthedProjectsRouteRouteChildren: AuthedProjectsRouteRouteChildren = {
  AuthedProjectsNewRoute: AuthedProjectsNewRoute,
  AuthedProjectsIndexRoute: AuthedProjectsIndexRoute,
  AuthedProjectsProjectIdEditRoute: AuthedProjectsProjectIdEditRoute,
  AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
}

const AuthedProjectsRouteRouteWithChildren =
  AuthedProjectsRouteRoute._addFileChildren(AuthedProjectsRouteRouteChildren)

interface AuthedTasksRouteRouteChildren {
  AuthedTasksTaskIdRoute: typeof AuthedTasksTaskIdRoute
  AuthedTasksNewRoute: typeof AuthedTasksNewRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
}

const AuthedTasksRouteRouteChildren: AuthedTasksRouteRouteChildren = {
  AuthedTasksTaskIdRoute: AuthedTasksTaskIdRoute,
  AuthedTasksNewRoute: AuthedTasksNewRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
}

const AuthedTasksRouteRouteWithChildren =
  AuthedTasksRouteRoute._addFileChildren(AuthedTasksRouteRouteChildren)

interface AuthedWatchesRouteRouteChildren {
  AuthedWatchesNewRoute: typeof AuthedWatchesNewRoute
  AuthedWatchesIndexRoute: typeof AuthedWatchesIndexRoute
  AuthedWatchesWatchIdEditRoute: typeof AuthedWatchesWatchIdEditRoute
  AuthedWatchesWatchIdIndexRoute: typeof AuthedWatchesWatchIdIndexRoute
}

const AuthedWatchesRouteRouteChildren: AuthedWatchesRouteRouteChildren = {
  AuthedWatchesNewRoute: AuthedWatchesNewRoute,
  AuthedWatchesIndexRoute: AuthedWatchesIndexRoute,
  AuthedWatchesWatchIdEditRoute: AuthedWatchesWatchIdEditRoute,
  AuthedWatchesWatchIdIndexRoute: AuthedWatchesWatchIdIndexRoute,
}

const AuthedWatchesRouteRouteWithChildren =
  AuthedWatchesRouteRoute._addFileChildren(AuthedWatchesRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedContactsRouteRoute: typeof AuthedContactsRouteRouteWithChildren
  AuthedDealsRouteRoute: typeof AuthedDealsRouteRouteWithChildren
  AuthedDocumentsRouteRoute: typeof AuthedDocumentsRouteRouteWithChildren
  AuthedInboxRouteRoute: typeof AuthedInboxRouteRouteWithChildren
  AuthedInteractionsRouteRoute: typeof AuthedInteractionsRouteRouteWithChildren
  AuthedOrganizationsRouteRoute: typeof AuthedOrganizationsRouteRouteWithChildren
  AuthedProjectsRouteRoute: typeof AuthedProjectsRouteRouteWithChildren
  AuthedTasksRouteRoute: typeof AuthedTasksRouteRouteWithChildren
  AuthedWatchesRouteRoute: typeof AuthedWatchesRouteRouteWithChildren
  AuthedCaptureRoute: typeof AuthedCaptureRoute
  AuthedNumbersRoute: typeof AuthedNumbersRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedSystemRoute: typeof AuthedSystemRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountMfaRoute: typeof AuthedAccountMfaRoute
  AuthedAccountPasswordRoute: typeof AuthedAccountPasswordRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedContactsRouteRoute: AuthedContactsRouteRouteWithChildren,
  AuthedDealsRouteRoute: AuthedDealsRouteRouteWithChildren,
  AuthedDocumentsRouteRoute: AuthedDocumentsRouteRouteWithChildren,
  AuthedInboxRouteRoute: AuthedInboxRouteRouteWithChildren,
  AuthedInteractionsRouteRoute: AuthedInteractionsRouteRouteWithChildren,
  AuthedOrganizationsRouteRoute: AuthedOrganizationsRouteRouteWithChildren,
  AuthedProjectsRouteRoute: AuthedProjectsRouteRouteWithChildren,
  AuthedTasksRouteRoute: AuthedTasksRouteRouteWithChildren,
  AuthedWatchesRouteRoute: AuthedWatchesRouteRouteWithChildren,
  AuthedCaptureRoute: AuthedCaptureRoute,
  AuthedNumbersRoute: AuthedNumbersRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedSystemRoute: AuthedSystemRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountMfaRoute: AuthedAccountMfaRoute,
  AuthedAccountPasswordRoute: AuthedAccountPasswordRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
