from datetime import date, datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import Computed, Date, DateTime, ForeignKey, Numeric, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base
from app.models.contact import Contact
from app.models.organization import Organization

# The pipeline, in order.
#
# One enum, not a stage plus a separate won/lost flag — two fields describing
# the same thing drift apart, and then "is this deal open?" has two answers.
#
# Winning is not the end of it: an engagement billed per hour worked *starts*
# when it is won, so `running` and `completed` sit after `won`. Without them
# every long engagement leaves the board the day the work begins.
OPEN_STAGES = ("lead", "qualified", "proposal", "negotiation")
WON_STAGES = ("won", "running", "completed")
DEAL_STAGES = OPEN_STAGES + WON_STAGES + ("lost",)

# Decided one way or the other — this is where `closed_at` gets stamped.
DECIDED_STAGES = WON_STAGES + ("lost",)
# Nothing left to do. Everything else still belongs on the board.
FINISHED_STAGES = ("completed", "lost")
ACTIVE_STAGES = OPEN_STAGES + ("won", "running")

# How a deal is priced. A single `value` column cannot describe both a
# fixed-price bid and an open-ended engagement billed by the day without
# forcing a lie in one direction or the other.
VALUE_TYPES = ("fixed", "rate_based", "retainer")
RATE_UNITS = ("hour", "day", "week", "month")

# Derived, and generated by Postgres rather than by the application, so it
# cannot drift from the columns it is computed from and T28 can SUM it directly.
#
# NULL means "genuinely open-ended", never zero: a rate with no volume estimate
# is a real deal whose total nobody knows yet. A pipeline sum has to report
# those as a separate count — summing them as 0 is how a day-rate-heavy
# pipeline reads as empty.
#
# Units are never converted. Multiplying a day rate by a volume estimated in
# months would need an invented days-per-month constant, which is the same
# silent lie the single `value` column was.
_EXPECTED_VALUE_SQL = """
CASE
    WHEN value_type = 'fixed' THEN fixed_value
    WHEN rate IS NOT NULL
     AND estimated_volume IS NOT NULL
     AND rate_unit = volume_unit
        THEN round(rate * estimated_volume, 2)
    ELSE NULL
END
"""


class Deal(Base):
    """An opportunity: a conversation that might become money.

    The hole the CRM had until now — a contact and a pile of interactions could
    not say what was being sold, for how much, or whether it came off.
    """

    __tablename__ = "deals"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(ForeignKey("user.id", ondelete="CASCADE"), index=True)
    title: Mapped[str]

    # --- What it is worth -------------------------------------------------
    # Money is Numeric, never Float: binary floating point cannot hold 0.1, so
    # a pipeline summed from floats stops matching the invoices it predicts.
    value_type: Mapped[str] = mapped_column(String, default="fixed", server_default="fixed")
    # Set for value_type == "fixed": the contract sum.
    fixed_value: Mapped[Decimal | None] = mapped_column(Numeric(14, 2))
    # Set for the rate-based and retainer cases.
    rate: Mapped[Decimal | None] = mapped_column(Numeric(14, 2))
    rate_unit: Mapped[str | None] = mapped_column(String)
    # A planning figure, not a cap and not a commitment — "~3 days a week for
    # six months". NULL is meaningful: the engagement is genuinely open-ended.
    estimated_volume: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    volume_unit: Mapped[str | None] = mapped_column(String)
    # Unconstrained precision so no product of rate and volume can overflow it.
    expected_value: Mapped[Decimal | None] = mapped_column(
        Numeric(), Computed(_EXPECTED_VALUE_SQL, persisted=True)
    )
    # Per deal, not per instance: one operator can quote in EUR and bill a
    # foreign client in USD, and a pipeline total that adds the two is a lie.
    currency: Mapped[str] = mapped_column(String(3), default="EUR", server_default="EUR")

    # --- Where it stands --------------------------------------------------
    # Free-form column constrained to DEAL_STAGES by the Pydantic schema — same
    # choice as Interaction.kind. A native Postgres enum would turn "add a
    # stage" into an ALTER TYPE migration, which is the wrong trade for a
    # pipeline the operator is still shaping.
    stage: Mapped[str] = mapped_column(String, default="lead", server_default="lead", index=True)

    expected_close_date: Mapped[date | None] = mapped_column(Date, index=True)
    # 0–100, enforced by the schema. Set automatically once decided: won is 100,
    # lost is 0, so a weighted pipeline does not keep counting a settled deal.
    probability: Mapped[int | None]
    # Only meaningful while stage == "lost"; cleared when a deal is reopened.
    lost_reason: Mapped[str | None]
    # When it was decided. expected_close_date is the forecast and stays put for
    # comparison — "did we call it right?" needs both.
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    notes: Mapped[str | None]

    # SET NULL on both, like Contact.organization_id: deleting the person or the
    # company must never delete the record of what was sold to them.
    contact_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("contacts.id", ondelete="SET NULL"), index=True
    )
    organization_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("organizations.id", ondelete="SET NULL"), index=True
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # selectin for the same reason as Contact.organization: a deal is always
    # rendered with who it is with, and a page of 50 would be 100 extra queries.
    contact: Mapped[Contact | None] = relationship(lazy="selectin")
    organization: Mapped[Organization | None] = relationship(lazy="selectin")

    @property
    def contact_name(self) -> str | None:
        """Denormalised for reads, so a deal list needs no second request."""
        return self.contact.name if self.contact is not None else None

    @property
    def organization_name(self) -> str | None:
        return self.organization.name if self.organization is not None else None

    @property
    def is_open(self) -> bool:
        """Still being competed for — not yet won or lost."""
        return self.stage in OPEN_STAGES

    @property
    def is_won(self) -> bool:
        """Came off, whether the work has started, is running or is finished."""
        return self.stage in WON_STAGES

    @property
    def is_active(self) -> bool:
        """Still belongs on the board: not completed, not lost."""
        return self.stage in ACTIVE_STAGES

    @property
    def is_open_ended(self) -> bool:
        """Priced by rate with no volume estimate, so no total can be derived.

        The flag a pipeline total needs in order to report "€48k across 4 deals,
        plus 2 open-ended" instead of quietly counting these as zero.
        """
        return self.value_type != "fixed" and self.estimated_volume is None
