"""Deals: CRUD, how a deal is priced, and the stage transition.

There was nowhere to record that a conversation became an opportunity. These
tests pin the replacement, and they cluster around the two things that are not
plain CRUD:

*Value is not one number.* A fixed-price bid has a contract sum; an engagement
billed per day worked has a rate and possibly no end at all. `expected_value` is
generated by Postgres from whichever shape applies, and is **NULL, never 0**,
when no total can be derived — because summing open-ended deals as zero is how a
day-rate-heavy pipeline reads as empty.

*A stage is not a label.* Arriving in a decided stage stamps `closed_at`, pins
the probability to 100 or 0, and decides whether a lost reason may exist at all.
Winning does not finish the work, so `running` and `completed` sit after `won`.
PATCH has to apply exactly the same rules as the stage endpoint, or a deal's
history depends on which button was pressed.
"""

from typing import Any

from httpx2 import AsyncClient

from tests.conftest import Account, create_resource


async def _deal(client: AsyncClient, account: Account, **fields: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {"title": "Website relaunch"}
    payload.update(fields)
    return await create_resource(client, account, "/deals/", payload)


async def test_a_deal_survives_a_full_round_trip(client: AsyncClient, alice: Account) -> None:
    created = await _deal(
        client,
        alice,
        title="Website relaunch",
        fixed_value="12500.00",
        currency="EUR",
        stage="proposal",
        expected_close_date="2026-11-30",
        probability=60,
        notes="Waiting on their design sign-off.",
    )
    assert created["fixed_value"] == "12500.00"
    assert created["expected_value"] == "12500.00"
    assert created["currency"] == "EUR"
    assert created["stage"] == "proposal"
    assert created["expected_close_date"] == "2026-11-30"
    assert created["probability"] == 60
    assert created["is_open"] is True
    assert created["closed_at"] is None

    fetched = await client.get(f"/deals/{created['id']}", headers=alice.headers)
    assert fetched.status_code == 200
    assert fetched.json()["notes"] == "Waiting on their design sign-off."

    patched = await client.patch(
        f"/deals/{created['id']}", json={"fixed_value": "14000.00"}, headers=alice.headers
    )
    assert patched.status_code == 200
    assert patched.json()["fixed_value"] == "14000.00"
    # The generated column followed the edit.
    assert patched.json()["expected_value"] == "14000.00"
    assert patched.json()["title"] == "Website relaunch"

    deleted = await client.delete(f"/deals/{created['id']}", headers=alice.headers)
    assert deleted.status_code == 204
    assert (await client.get(f"/deals/{created['id']}", headers=alice.headers)).status_code == 404


async def test_a_bare_deal_starts_open_at_the_top_of_the_pipeline(
    client: AsyncClient, alice: Account
) -> None:
    created = await _deal(client, alice)

    assert created["stage"] == "lead"
    assert created["currency"] == "EUR"
    assert created["value_type"] == "fixed"
    assert created["is_open"] is True
    assert created["is_won"] is False
    assert created["is_active"] is True
    assert created["expected_value"] is None
    assert created["probability"] is None
    assert created["closed_at"] is None
    assert created["lost_reason"] is None


# --- What it is worth -------------------------------------------------------


async def test_a_rate_based_deal_with_an_estimate_derives_its_total(
    client: AsyncClient, alice: Account
) -> None:
    created = await _deal(
        client,
        alice,
        value_type="rate_based",
        rate="800.00",
        rate_unit="day",
        estimated_volume="60",
        volume_unit="day",
    )

    # 800 × 60, computed by Postgres rather than by the application, so it
    # cannot drift from the columns it derives from.
    assert created["expected_value"] == "48000.00"
    assert created["is_open_ended"] is False


async def test_an_open_ended_engagement_has_no_total_rather_than_a_zero(
    client: AsyncClient, alice: Account
) -> None:
    # The case a single `value` column could not express: a real deal, at a
    # known rate, with no agreed end. Counting it as 0 is how a day-rate-heavy
    # pipeline reads as empty.
    created = await _deal(
        client,
        alice,
        title="Ongoing platform work",
        value_type="rate_based",
        rate="800.00",
        rate_unit="day",
    )

    assert created["expected_value"] is None
    assert created["is_open_ended"] is True
    assert created["rate"] == "800.00"


async def test_a_retainer_is_priced_per_month(client: AsyncClient, alice: Account) -> None:
    created = await _deal(
        client,
        alice,
        value_type="retainer",
        rate="2000.00",
        rate_unit="month",
        estimated_volume="12",
        volume_unit="month",
    )

    assert created["expected_value"] == "24000.00"
    assert created["is_open_ended"] is False


async def test_mismatched_units_derive_nothing_rather_than_inventing_a_factor(
    client: AsyncClient, alice: Account
) -> None:
    # A day rate against a volume estimated in months would need an invented
    # days-per-month constant — the same silent lie a single value column was.
    created = await _deal(
        client,
        alice,
        value_type="rate_based",
        rate="800.00",
        rate_unit="day",
        estimated_volume="6",
        volume_unit="month",
    )

    assert created["expected_value"] is None
    # It is estimated, though, so it is not open-ended either.
    assert created["is_open_ended"] is False


async def test_a_deal_cannot_be_priced_two_ways_at_once(
    client: AsyncClient, alice: Account
) -> None:
    fixed_with_a_rate = await client.post(
        "/deals/",
        json={"title": "X", "value_type": "fixed", "fixed_value": "100.00", "rate": "800.00"},
        headers=alice.headers,
    )
    assert fixed_with_a_rate.status_code == 422

    rate_with_a_sum = await client.post(
        "/deals/",
        json={"title": "X", "value_type": "rate_based", "fixed_value": "100.00"},
        headers=alice.headers,
    )
    assert rate_with_a_sum.status_code == 422


async def test_a_quantity_without_its_unit_is_refused(client: AsyncClient, alice: Account) -> None:
    # "60" is not an estimate, and nothing can be multiplied by it.
    no_rate_unit = await client.post(
        "/deals/",
        json={"title": "X", "value_type": "rate_based", "rate": "800.00"},
        headers=alice.headers,
    )
    assert no_rate_unit.status_code == 422

    no_volume_unit = await client.post(
        "/deals/",
        json={
            "title": "X",
            "value_type": "rate_based",
            "rate": "800.00",
            "rate_unit": "day",
            "estimated_volume": "60",
        },
        headers=alice.headers,
    )
    assert no_volume_unit.status_code == 422


async def test_patching_a_rate_onto_a_fixed_price_deal_is_refused(
    client: AsyncClient, alice: Account
) -> None:
    # The request never mentions value_type, so the check has to run against the
    # row as it would be *after* the patch.
    deal = await _deal(client, alice, fixed_value="1000.00")

    response = await client.patch(
        f"/deals/{deal['id']}",
        json={"rate": "800.00", "rate_unit": "day"},
        headers=alice.headers,
    )

    assert response.status_code == 422


async def test_repricing_a_deal_drops_the_other_shapes_fields(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice, fixed_value="1000.00")

    repriced = await client.patch(
        f"/deals/{deal['id']}",
        json={
            "value_type": "rate_based",
            "rate": "900.00",
            "rate_unit": "day",
            "estimated_volume": "10",
            "volume_unit": "day",
        },
        headers=alice.headers,
    )

    assert repriced.status_code == 200
    # Switching shape is a deliberate re-pricing, so the contract sum goes
    # rather than sitting alongside a day rate.
    assert repriced.json()["fixed_value"] is None
    assert repriced.json()["expected_value"] == "9000.00"


async def test_money_keeps_its_scale_rather_than_becoming_a_float(
    client: AsyncClient, alice: Account
) -> None:
    created = await _deal(client, alice, fixed_value="0.10")
    assert created["fixed_value"] == "0.10"
    assert created["expected_value"] == "0.10"

    big = await _deal(client, alice, fixed_value="999999999999.99")
    assert big["fixed_value"] == "999999999999.99"


async def test_an_unusable_value_is_rejected(client: AsyncClient, alice: Account) -> None:
    for bad in ["-1", "1.005", "9999999999999999"]:
        response = await client.post(
            "/deals/", json={"title": "Bad", "fixed_value": bad}, headers=alice.headers
        )
        assert response.status_code == 422, f"{bad} should be refused"


async def test_the_currency_is_normalised_and_checked(client: AsyncClient, alice: Account) -> None:
    # "eur" and "EUR" must not become two columns in a pipeline report.
    created = await _deal(client, alice, currency="usd")
    assert created["currency"] == "USD"

    for bad in ["EURO", "E", "12€"]:
        response = await client.post(
            "/deals/", json={"title": "Bad", "currency": bad}, headers=alice.headers
        )
        assert response.status_code == 422, f"{bad} should be refused"


async def test_an_unknown_stage_or_unit_and_an_impossible_probability_are_rejected(
    client: AsyncClient, alice: Account
) -> None:
    for payload in (
        {"title": "X", "stage": "haggling"},
        {"title": "X", "probability": 101},
        {"title": "X", "probability": -1},
        {"title": "X", "value_type": "guesswork"},
        {"title": "X", "value_type": "rate_based", "rate": "1.00", "rate_unit": "fortnight"},
    ):
        response = await client.post("/deals/", json=payload, headers=alice.headers)
        assert response.status_code == 422, f"{payload} should be refused"


# --- Where it stands --------------------------------------------------------


async def test_winning_a_deal_closes_it_at_full_probability(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice, stage="negotiation", probability=70)

    response = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "won"}, headers=alice.headers
    )

    assert response.status_code == 200
    won = response.json()
    assert won["stage"] == "won"
    assert won["is_open"] is False
    assert won["is_won"] is True
    assert won["closed_at"] is not None
    # Banked money must stop being forecast at 70%.
    assert won["probability"] == 100
    assert won["lost_reason"] is None


async def test_a_won_deal_stays_on_the_board_while_the_work_runs(
    client: AsyncClient, alice: Account
) -> None:
    # Winning an engagement billed by the day *starts* it. Without somewhere for
    # "won and running" to sit, every long engagement would leave the board the
    # day the work began.
    deal = await _deal(
        client, alice, value_type="rate_based", rate="800.00", rate_unit="day", stage="negotiation"
    )
    await client.post(f"/deals/{deal['id']}/stage", json={"stage": "won"}, headers=alice.headers)

    running = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "running"}, headers=alice.headers
    )
    assert running.json()["is_active"] is True
    assert running.json()["is_won"] is True
    assert running.json()["is_open"] is False

    completed = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "completed"}, headers=alice.headers
    )
    # Finished: still won, but off the board.
    assert completed.json()["is_won"] is True
    assert completed.json()["is_active"] is False


async def test_starting_and_finishing_the_work_does_not_move_the_date_it_was_won_on(
    client: AsyncClient, alice: Account
) -> None:
    # closed_at is when the deal was *decided*, not when the work ended.
    deal = await _deal(client, alice)
    won = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "won"}, headers=alice.headers
    )
    closed_at = won.json()["closed_at"]

    for stage in ("running", "completed"):
        moved = await client.post(
            f"/deals/{deal['id']}/stage", json={"stage": stage}, headers=alice.headers
        )
        assert moved.json()["closed_at"] == closed_at, f"{stage} moved the close date"

    # Nor does a plain edit, or re-sending the stage it is already in.
    edited = await client.patch(
        f"/deals/{deal['id']}", json={"title": "Phase 1"}, headers=alice.headers
    )
    assert edited.json()["closed_at"] == closed_at


async def test_changing_the_decision_does_restamp_the_close(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice)
    won = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "won"}, headers=alice.headers
    )

    lost = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "lost"}, headers=alice.headers
    )

    # Going from won to lost is a new decision, not a step through delivery.
    assert lost.json()["closed_at"] != won.json()["closed_at"]
    assert lost.json()["probability"] == 0


async def test_losing_a_deal_records_the_reason_at_zero_probability(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice, stage="proposal", probability=40)

    response = await client.post(
        f"/deals/{deal['id']}/stage",
        json={"stage": "lost", "lost_reason": "Went with a cheaper agency"},
        headers=alice.headers,
    )

    assert response.status_code == 200
    lost = response.json()
    assert lost["stage"] == "lost"
    assert lost["is_won"] is False
    assert lost["is_active"] is False
    assert lost["closed_at"] is not None
    assert lost["probability"] == 0
    assert lost["lost_reason"] == "Went with a cheaper agency"


async def test_a_loss_may_go_unexplained(client: AsyncClient, alice: Account) -> None:
    # Requiring a reason would stall a kanban drag behind a dialog, and an
    # unexplained loss still beats a deal left sitting in "negotiation".
    deal = await _deal(client, alice)

    response = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "lost"}, headers=alice.headers
    )

    assert response.status_code == 200
    assert response.json()["lost_reason"] is None
    assert response.json()["closed_at"] is not None


async def test_reopening_a_closed_deal_clears_the_close_and_its_reason(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice)
    await client.post(
        f"/deals/{deal['id']}/stage",
        json={"stage": "lost", "lost_reason": "Budget frozen"},
        headers=alice.headers,
    )

    reopened = await client.post(
        f"/deals/{deal['id']}/stage", json={"stage": "negotiation"}, headers=alice.headers
    )

    assert reopened.status_code == 200
    assert reopened.json()["stage"] == "negotiation"
    assert reopened.json()["is_open"] is True
    # It is in play again, so last year's loss must not still be attached.
    assert reopened.json()["closed_at"] is None
    assert reopened.json()["lost_reason"] is None


async def test_a_deal_can_be_entered_already_running(client: AsyncClient, alice: Account) -> None:
    # Work agreed before anyone opened the CRM: the decided-stage bookkeeping
    # has to run on create too, not only on a transition.
    created = await _deal(client, alice, stage="running", fixed_value="900.00")

    assert created["is_won"] is True
    assert created["is_active"] is True
    assert created["closed_at"] is not None
    assert created["probability"] == 100


async def test_patching_the_stage_obeys_the_same_rules_as_the_stage_endpoint(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice, probability=25)

    patched = await client.patch(
        f"/deals/{deal['id']}",
        json={"stage": "lost", "lost_reason": "No response"},
        headers=alice.headers,
    )

    assert patched.status_code == 200
    assert patched.json()["closed_at"] is not None
    assert patched.json()["probability"] == 0
    assert patched.json()["lost_reason"] == "No response"


async def test_a_probability_sent_with_a_close_loses_to_the_stage(
    client: AsyncClient, alice: Account
) -> None:
    deal = await _deal(client, alice)

    patched = await client.patch(
        f"/deals/{deal['id']}", json={"stage": "won", "probability": 50}, headers=alice.headers
    )

    assert patched.json()["probability"] == 100


async def test_a_lost_reason_without_a_loss_is_refused(client: AsyncClient, alice: Account) -> None:
    created = await client.post(
        "/deals/",
        json={"title": "X", "stage": "proposal", "lost_reason": "Too expensive"},
        headers=alice.headers,
    )
    assert created.status_code == 422

    deal = await _deal(client, alice)
    patched = await client.patch(
        f"/deals/{deal['id']}", json={"lost_reason": "Too expensive"}, headers=alice.headers
    )
    assert patched.status_code == 422

    moved = await client.post(
        f"/deals/{deal['id']}/stage",
        json={"stage": "won", "lost_reason": "Too expensive"},
        headers=alice.headers,
    )
    assert moved.status_code == 422


async def test_winning_a_lost_deal_clears_its_reason_rather_than_failing(
    client: AsyncClient, alice: Account
) -> None:
    # The reason is already on the row; only a reason the caller *sends* with a
    # non-lost stage is a contradiction.
    deal = await _deal(client, alice)
    await client.post(
        f"/deals/{deal['id']}/stage",
        json={"stage": "lost", "lost_reason": "Budget frozen"},
        headers=alice.headers,
    )

    won = await client.patch(f"/deals/{deal['id']}", json={"stage": "won"}, headers=alice.headers)

    assert won.status_code == 200
    assert won.json()["lost_reason"] is None
    assert won.json()["probability"] == 100


# --- Who it is with ---------------------------------------------------------


async def test_a_deal_reads_back_who_it_is_with(client: AsyncClient, alice: Account) -> None:
    organization = await create_resource(client, alice, "/organizations/", {"name": "ACME"})
    contact = await create_resource(
        client, alice, "/contacts/", {"name": "Ada Lovelace", "organization_id": organization["id"]}
    )

    created = await _deal(
        client, alice, contact_id=contact["id"], organization_id=organization["id"]
    )

    assert created["contact_id"] == contact["id"]
    # Denormalised so a list row needs no request per deal.
    assert created["contact_name"] == "Ada Lovelace"
    assert created["organization_name"] == "ACME"

    listed = await client.get("/deals/", headers=alice.headers)
    assert listed.json()["items"][0]["organization_name"] == "ACME"


async def test_deleting_a_contact_keeps_the_deal(client: AsyncClient, alice: Account) -> None:
    contact = await create_resource(client, alice, "/contacts/", {"name": "Ada"})
    deal = await _deal(client, alice, fixed_value="5000.00", contact_id=contact["id"])

    assert (
        await client.delete(f"/contacts/{contact['id']}", headers=alice.headers)
    ).status_code == 204

    # Losing the person must never delete the record of what was sold to them.
    survivor = await client.get(f"/deals/{deal['id']}", headers=alice.headers)
    assert survivor.status_code == 200
    assert survivor.json()["contact_id"] is None
    assert survivor.json()["contact_name"] is None
    assert survivor.json()["fixed_value"] == "5000.00"


async def test_deleting_an_organization_keeps_the_deal(client: AsyncClient, alice: Account) -> None:
    organization = await create_resource(client, alice, "/organizations/", {"name": "ACME"})
    deal = await _deal(client, alice, organization_id=organization["id"])

    assert (
        await client.delete(f"/organizations/{organization['id']}", headers=alice.headers)
    ).status_code == 204

    survivor = await client.get(f"/deals/{deal['id']}", headers=alice.headers)
    assert survivor.status_code == 200
    assert survivor.json()["organization_id"] is None


async def test_an_unknown_contact_or_organization_is_refused(
    client: AsyncClient, alice: Account
) -> None:
    missing = "00000000-0000-0000-0000-000000000001"

    assert (
        await client.post(
            "/deals/", json={"title": "X", "contact_id": missing}, headers=alice.headers
        )
    ).status_code == 404
    assert (
        await client.post(
            "/deals/", json={"title": "X", "organization_id": missing}, headers=alice.headers
        )
    ).status_code == 404

    deal = await _deal(client, alice)
    assert (
        await client.patch(
            f"/deals/{deal['id']}", json={"contact_id": missing}, headers=alice.headers
        )
    ).status_code == 404


async def test_a_deal_cannot_be_filed_against_another_users_customer(
    client: AsyncClient, alice: Account, bob: Account
) -> None:
    alices_contact = await create_resource(client, alice, "/contacts/", {"name": "Ada"})
    alices_company = await create_resource(client, alice, "/organizations/", {"name": "ACME"})

    assert (
        await client.post(
            "/deals/",
            json={"title": "Bob's deal", "contact_id": alices_contact["id"]},
            headers=bob.headers,
        )
    ).status_code == 404
    assert (
        await client.post(
            "/deals/",
            json={"title": "Bob's deal", "organization_id": alices_company["id"]},
            headers=bob.headers,
        )
    ).status_code == 404

    bobs_deal = await _deal(client, bob, title="Bob's deal")
    patched = await client.patch(
        f"/deals/{bobs_deal['id']}",
        json={"organization_id": alices_company["id"]},
        headers=bob.headers,
    )
    assert patched.status_code == 404
    # And nothing leaked back on the read.
    assert (await client.get(f"/deals/{bobs_deal['id']}", headers=bob.headers)).json()[
        "organization_name"
    ] is None


# --- Finding them again -----------------------------------------------------


async def test_the_list_answers_the_four_questions_the_board_asks(
    client: AsyncClient, alice: Account
) -> None:
    await _deal(client, alice, title="Bidding", stage="proposal")
    await _deal(client, alice, title="Agreed", stage="won")
    await _deal(client, alice, title="Delivering", stage="running")
    await _deal(client, alice, title="Delivered", stage="completed")
    await _deal(client, alice, title="Gone", stage="lost")

    async def titles(query: str) -> set[str]:
        response = await client.get(f"/deals/?status={query}", headers=alice.headers)
        assert response.status_code == 200
        return {d["title"] for d in response.json()["items"]}

    # What am I still competing for?
    assert await titles("open") == {"Bidding"}
    # What is on my plate? A running engagement has to stay on the board.
    assert await titles("active") == {"Bidding", "Agreed", "Delivering"}
    # What came off, whatever state the work is in?
    assert await titles("won") == {"Agreed", "Delivering", "Delivered"}
    # What is done with?
    assert await titles("finished") == {"Delivered", "Gone"}

    one_stage = await client.get("/deals/?stage=running", headers=alice.headers)
    assert one_stage.json()["total"] == 1
    assert one_stage.json()["items"][0]["title"] == "Delivering"


async def test_deals_can_be_filtered_by_customer_and_searched_by_title(
    client: AsyncClient, alice: Account
) -> None:
    organization = await create_resource(client, alice, "/organizations/", {"name": "ACME"})
    contact = await create_resource(client, alice, "/contacts/", {"name": "Ada"})
    await _deal(client, alice, title="ACME relaunch", organization_id=organization["id"])
    await _deal(client, alice, title="Ada's retainer", contact_id=contact["id"])
    await _deal(client, alice, title="Unattached audit")

    by_org = await client.get(
        f"/deals/?organization_id={organization['id']}", headers=alice.headers
    )
    assert by_org.json()["total"] == 1
    assert by_org.json()["items"][0]["title"] == "ACME relaunch"

    by_contact = await client.get(f"/deals/?contact_id={contact['id']}", headers=alice.headers)
    assert by_contact.json()["total"] == 1

    by_title = await client.get("/deals/?search=retainer", headers=alice.headers)
    assert by_title.json()["total"] == 1
    assert by_title.json()["items"][0]["title"] == "Ada's retainer"


async def test_the_soonest_close_comes_first_and_undated_deals_come_last(
    client: AsyncClient, alice: Account
) -> None:
    await _deal(client, alice, title="No date")
    await _deal(client, alice, title="December", expected_close_date="2026-12-01")
    await _deal(client, alice, title="September", expected_close_date="2026-09-15")

    response = await client.get("/deals/", headers=alice.headers)

    # Work-it-next order. A deal with no date is not urgent, so it sorts last
    # rather than where ASC would put NULLs.
    assert [d["title"] for d in response.json()["items"]] == ["September", "December", "No date"]


async def test_the_list_reports_the_total_beyond_the_page(
    client: AsyncClient, alice: Account
) -> None:
    for index in range(5):
        await _deal(client, alice, title=f"Deal {index}")

    response = await client.get("/deals/?limit=2", headers=alice.headers)

    assert response.status_code == 200
    page = response.json()
    assert len(page["items"]) == 2
    assert page["total"] == 5
    assert page["limit"] == 2


async def test_a_deal_without_a_title_is_rejected(client: AsyncClient, alice: Account) -> None:
    response = await client.post("/deals/", json={"fixed_value": "100.00"}, headers=alice.headers)

    assert response.status_code == 422


async def test_a_bad_page_size_is_rejected(client: AsyncClient, alice: Account) -> None:
    assert (await client.get("/deals/?limit=0", headers=alice.headers)).status_code == 422
    assert (await client.get("/deals/?limit=500", headers=alice.headers)).status_code == 422
    assert (await client.get("/deals/?skip=-1", headers=alice.headers)).status_code == 422


async def test_the_stage_endpoint_is_owner_only(
    client: AsyncClient, alice: Account, bob: Account
) -> None:
    deal = await _deal(client, alice)

    assert (
        await client.post(f"/deals/{deal['id']}/stage", json={"stage": "won"}, headers=bob.headers)
    ).status_code == 404
    assert (
        await client.post(f"/deals/{deal['id']}/stage", json={"stage": "won"})
    ).status_code == 401
    # And Alice's deal is untouched.
    assert (await client.get(f"/deals/{deal['id']}", headers=alice.headers)).json()[
        "stage"
    ] == "lead"
