from datetime import date, datetime
from decimal import Decimal
from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, Field, StringConstraints

DealStage = Literal[
    "lead",
    "qualified",
    "proposal",
    "negotiation",
    # Winning starts the work rather than ending the deal, so there is somewhere
    # for a running engagement to sit instead of dropping off the board.
    "won",
    "running",
    "completed",
    "lost",
]

# How a deal is priced. A fixed-price bid has a contract sum; an engagement
# billed per hour worked has a rate and possibly no end at all.
DealValueType = Literal["fixed", "rate_based", "retainer"]
RateUnit = Literal["hour", "day", "week", "month"]

# What the list is being asked for. Coarser than `stage`, and the questions the
# UI actually asks: what am I competing for, what is on my plate, what came off,
# what is done with.
DealStatus = Literal["open", "active", "won", "finished"]

# ISO 4217, normalised to upper case so "eur" and "EUR" are one currency rather
# than two columns in a pipeline report.
Currency = Annotated[str, StringConstraints(to_upper=True, pattern=r"^[A-Za-z]{3}$")]

# 14 digits with 2 after the point — up to 999,999,999,999.99, which is more
# headroom than a solo business needs and still fits Numeric(14, 2).
Money = Annotated[Decimal, Field(ge=0, max_digits=14, decimal_places=2)]
# Hours or days, so 12 digits is already absurd headroom.
Volume = Annotated[Decimal, Field(ge=0, max_digits=12, decimal_places=2)]

Probability = Annotated[int, Field(ge=0, le=100)]


class DealValueFields(BaseModel):
    """The pricing half of a deal, shared by create and update.

    Which of these may be set depends on `value_type`; the router refuses the
    combinations that contradict each other, so a row can never claim to be
    both a fixed bid and a day rate.
    """

    value_type: DealValueType = "fixed"
    # value_type == "fixed": the contract sum.
    fixed_value: Money | None = None
    # value_type == "rate_based" or "retainer".
    rate: Money | None = None
    rate_unit: RateUnit | None = None
    # A planning figure, not a cap. None means genuinely open-ended, which is
    # why `expected_value` comes back null rather than zero.
    estimated_volume: Volume | None = None
    volume_unit: RateUnit | None = None


class DealCreate(DealValueFields):
    title: str
    currency: Currency = "EUR"
    stage: DealStage = "lead"
    expected_close_date: date | None = None
    probability: Probability | None = None
    # Rejected unless the deal is actually lost — see _apply_stage in the router.
    lost_reason: str | None = None
    notes: str | None = None
    # Both optional: an inbound enquiry is a deal before it is a person, and a
    # tender is a deal with a contracting authority and no named contact yet.
    contact_id: UUID | None = None
    organization_id: UUID | None = None


# PATCH uses the same fields but all optional — only sent fields are updated
class DealUpdate(BaseModel):
    title: str | None = None
    value_type: DealValueType | None = None
    fixed_value: Money | None = None
    rate: Money | None = None
    rate_unit: RateUnit | None = None
    estimated_volume: Volume | None = None
    volume_unit: RateUnit | None = None
    currency: Currency | None = None
    stage: DealStage | None = None
    expected_close_date: date | None = None
    probability: Probability | None = None
    lost_reason: str | None = None
    notes: str | None = None
    contact_id: UUID | None = None
    organization_id: UUID | None = None


class DealStageChange(BaseModel):
    """Body of POST /deals/{id}/stage — the one move the pipeline is made of."""

    stage: DealStage
    # Sent with a move to "lost". Optional on purpose: requiring it would stall
    # a kanban drag behind a dialog, and an unexplained loss still beats a deal
    # left sitting in "negotiation" forever.
    lost_reason: str | None = None


class DealRead(BaseModel):
    id: UUID
    title: str

    value_type: DealValueType
    fixed_value: Decimal | None
    rate: Decimal | None
    rate_unit: RateUnit | None
    estimated_volume: Decimal | None
    volume_unit: RateUnit | None
    # Generated by the database: fixed_value, or rate × estimated_volume when
    # the two units agree. Null means no total can be derived — never zero.
    expected_value: Decimal | None
    # True when it is rate-priced with no volume estimate. A pipeline total has
    # to count these separately rather than adding them as nothing.
    is_open_ended: bool
    currency: str

    stage: DealStage
    expected_close_date: date | None
    probability: int | None
    lost_reason: str | None
    closed_at: datetime | None
    notes: str | None

    contact_id: UUID | None
    organization_id: UUID | None
    # Denormalised so a list row shows who the deal is with, without a request
    # per row — same reasoning as ContactRead.organization_name.
    contact_name: str | None
    organization_name: str | None

    # All derived from the stage rather than stored, so none of them can
    # disagree with it.
    is_open: bool
    is_won: bool
    is_active: bool

    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}
